print('Média de dois valores')
n1 = float(input('Digite um número: '))
n2 = float(input('Digite outro número: '))
n3 = float((n1 + n2) / 2)
print('A média entre {} e {} é {:.2f}'.format(n1, n2, n3))