print('Expecificação de Variavel')
valor=input('Digite alguma coisa:')
print('A classe dessa coisa é:',type(valor))
print('É printável?',valor.isprintable())
print('É um maiusculo?',valor.isupper())
print('É um minusculo?',valor.islower())
print('É um alfabético?',valor.isalpha())
print('É um alfanumérico?',valor.isalnum())
print('É um numérico?',valor.isnumeric())
print('Só tem espaço?',valor.isspace())
