print('Dobro, triplo e Raiz Quadrada')
n1 = int(input('Digite um valor: '))
n2 = int(n1 * 2)
n3 = int(n1 * 3)
n4 = int(n1 ** (1/2))
print('O dobro, o triplo e a raiz quadrada de {} é: {}, {} e {}'.format(n1, n2, n3, n4))